<Project>
  <Import Project="../Directory.Build.props" />
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../docs/causalia-icon.png"
          Pack="true"
          PackagePath=""
          Visible="false" />
  </ItemGroup>
</Project>
